[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.curl",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Packages.composer",
  "nodejs_20",
  "nodePackages.npm"
]

[phases.install]
cmds = [
  "echo '=== CHECK NODE ==='",
  "which node || echo 'NODE TIDAK ADA'",
  "echo '=== CHECK NPM ==='",
  "which npm || echo 'NPM TIDAK ADA'",
  
  "npm -v",
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm install"
  "php artisan db:seed --force",
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
